-- =============================================================
-- Egresados — schema inicial
-- =============================================================
-- Conceptos:
--   * Una ESCUELA agrupa GRUPOS (un grupo = un grado/año de egreso).
--   * Cada GRUPO contiene FAMILIAS, y cada FAMILIA puede tener uno o más ALUMNOS.
--   * Las EMPRESAS publican DESTINOS, cada destino tiene PLANES_VIAJE
--     (combinaciones de duración/transporte/forma de pago) y DOCUMENTOS adjuntos
--     que en una fase posterior van a ser procesados por IA.
--   * El flujo de votación es en dos etapas:
--       1) FECHAS_REUNION — la empresa propone fechas y las familias eligen.
--       2) VOTOS_PLAN — una vez vista la presentación, las familias rankean planes.
--   * PROFILES vincula auth.users (Supabase Auth) a su rol y a la entidad
--     correspondiente (empresa o familia).
-- =============================================================

-- =============================================================
-- Roles / Profiles
-- =============================================================
create type user_rol as enum ('super_admin', 'empresa_admin', 'familia');

create table profiles (
  user_id      uuid primary key references auth.users(id) on delete cascade,
  rol          user_rol not null,
  nombre       text,
  empresa_id   bigint, -- FK seteada más abajo (forward ref)
  familia_id   bigint, -- FK seteada más abajo
  created_at   timestamptz default now()
);

-- =============================================================
-- Escuelas / Grupos / Familias / Alumnos
-- =============================================================
create table escuelas (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  localidad   text,
  provincia   text,
  created_at  timestamptz default now()
);

create table grupos (
  id            bigint generated by default as identity primary key,
  escuela_id    bigint not null references escuelas(id) on delete cascade,
  anio_egreso   smallint not null,                -- ej: 2026
  grado         text,                             -- "6to A", "7mo B", "Secundario 5to"
  estado        text default 'activo',            -- activo | cerrado
  created_at    timestamptz default now(),
  unique (escuela_id, anio_egreso, grado)
);

create table familias (
  id          bigint generated by default as identity primary key,
  grupo_id    bigint not null references grupos(id) on delete cascade,
  apellido    text not null,
  email       text,
  telefono    text,
  created_at  timestamptz default now()
);

create table alumnos (
  id          bigint generated by default as identity primary key,
  familia_id  bigint not null references familias(id) on delete cascade,
  nombre      text not null,
  created_at  timestamptz default now()
);

alter table profiles add constraint profiles_familia_fk
  foreign key (familia_id) references familias(id) on delete set null;

-- =============================================================
-- Empresas / Destinos / Planes / Documentos
-- =============================================================
create table empresas (
  id              bigint generated by default as identity primary key,
  nombre          text not null,
  slug            text unique not null,
  contacto_email  text,
  contacto_tel    text,
  activo          boolean default true,
  created_at      timestamptz default now()
);

alter table profiles add constraint profiles_empresa_fk
  foreign key (empresa_id) references empresas(id) on delete cascade;

create table destinos (
  id          bigint generated by default as identity primary key,
  empresa_id  bigint not null references empresas(id) on delete cascade,
  nombre      text not null,                  -- "Carlos Paz / Córdoba"
  provincia   text,
  descripcion text,
  activo      boolean default true,
  created_at  timestamptz default now()
);

create table planes_viaje (
  id                bigint generated by default as identity primary key,
  destino_id        bigint not null references destinos(id) on delete cascade,
  transporte        text,                     -- "Bus" | "Avión"
  dias              smallint,
  noches            smallint,
  plan_pago         text,                     -- nombre del plan
  cantidad_cuotas   smallint,
  inscripcion       integer,
  reserva           integer,
  primera_cuota     integer,
  cuota_mensual     integer,
  anticipo_saldo    integer,
  total_final       integer,
  liberados         text,
  seguro            text,
  descuentos        text,
  actividades       text,
  vigencia          text,
  activo            boolean default true,
  created_at        timestamptz default now()
);
create index on planes_viaje (destino_id);

-- Documentos subidos por la empresa (PDFs, fotos, planillas).
-- procesado_estado controla el pipeline futuro de IA:
--   pendiente → procesando → procesado | error
-- datos_extraidos guarda el output estructurado del LLM (mock por ahora).
create table documentos (
  id                  bigint generated by default as identity primary key,
  destino_id          bigint references destinos(id) on delete cascade,
  plan_id             bigint references planes_viaje(id) on delete cascade,
  nombre              text not null,
  storage_path        text not null,          -- path en bucket "documentos"
  mime_type           text,
  size_bytes          bigint,
  procesado_estado    text default 'pendiente',
  datos_extraidos     jsonb,
  procesado_at        timestamptz,
  uploaded_by         uuid references auth.users(id),
  created_at          timestamptz default now(),
  check (destino_id is not null or plan_id is not null)
);
create index on documentos (destino_id);
create index on documentos (plan_id);
create index on documentos (procesado_estado);

-- =============================================================
-- Votación etapa 1: fechas de reunión
-- =============================================================
create table fechas_reunion (
  id           bigint generated by default as identity primary key,
  grupo_id     bigint not null references grupos(id) on delete cascade,
  empresa_id   bigint not null references empresas(id) on delete cascade,
  fecha        timestamptz not null,
  ubicacion    text,                          -- presencial, link, etc
  estado       text default 'propuesta',      -- propuesta | confirmada | cancelada | realizada
  created_by   uuid references auth.users(id),
  created_at   timestamptz default now()
);
create index on fechas_reunion (grupo_id);

create table votos_fecha (
  familia_id  bigint not null references familias(id) on delete cascade,
  fecha_id    bigint not null references fechas_reunion(id) on delete cascade,
  voto        boolean not null,               -- true=acepta, false=rechaza
  created_at  timestamptz default now(),
  primary key (familia_id, fecha_id)
);

-- =============================================================
-- Votación etapa 2: planes
-- =============================================================
-- Una familia rankea hasta 3 planes (prioridad 1/2/3).
create table votos_plan (
  id          bigint generated by default as identity primary key,
  familia_id  bigint not null references familias(id) on delete cascade,
  plan_id     bigint not null references planes_viaje(id) on delete cascade,
  prioridad   smallint not null check (prioridad between 1 and 3),
  comentario  text,
  created_at  timestamptz default now(),
  unique (familia_id, prioridad)
);

-- =============================================================
-- Correcciones (reportes de errores en los datos cargados)
-- =============================================================
create table correcciones (
  id              bigint generated by default as identity primary key,
  plan_id         bigint references planes_viaje(id) on delete cascade,
  destino_id      bigint references destinos(id) on delete cascade,
  campo           text not null,
  valor_actual    text,
  valor_correcto  text,
  comentario      text,
  reportado_by    uuid references auth.users(id),
  estado          text default 'pendiente',
  created_at      timestamptz default now()
);

-- =============================================================
-- LEGACY: tabla "planes" (mantenida para compatibilidad)
-- =============================================================
-- El frontend público actual lee de JSON locales; esta tabla espejo se mantiene
-- hasta migrar la UI a leer desde destinos+planes_viaje. NO usar para datos nuevos.
create table if not exists planes (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  empresa text not null,
  destino text not null,
  transporte text,
  dias smallint,
  noches smallint,
  plan_pago text,
  cantidad_cuotas smallint,
  inscripcion integer,
  reserva integer,
  primera_cuota integer,
  cuota_mensual integer,
  anticipo_saldo integer,
  total_final integer,
  liberados text,
  seguro text,
  descuentos text,
  actividades text,
  vigencia text
);

-- LEGACY: tabla "votos" (frontend público actual)
-- TODO: deprecar a favor de votos_plan + votos_fecha cuando el frontend migre.
create table if not exists votos (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  nombre text not null,
  destino text not null,
  empresa text,
  duracion text,
  prioridad smallint,
  plan_pago text,
  total_final integer,
  cuota_mensual integer,
  comentario text
);

-- =============================================================
-- RLS
-- =============================================================
-- Estrategia:
--   * Tablas de catálogo público (escuelas, empresas, destinos, planes_viaje):
--     lectura pública (anon), escritura solo por roles autorizados.
--   * Tablas de familia (familias, alumnos, votos_*):
--     escritura/lectura por la propia familia o por admins.
--   * profiles: cada user lee el suyo; super_admin lee todos.

-- Helper: ¿el user actual es super_admin?
create or replace function is_super_admin() returns boolean
  language sql stable security definer
  as $$ select exists (select 1 from profiles where user_id = auth.uid() and rol = 'super_admin') $$;

-- Helper: ¿el user actual es admin de la empresa pasada?
create or replace function is_empresa_admin(p_empresa_id bigint) returns boolean
  language sql stable security definer
  as $$ select exists (
    select 1 from profiles
    where user_id = auth.uid() and rol = 'empresa_admin' and empresa_id = p_empresa_id
  ) $$;

-- Helper: familia del user actual (devuelve familia_id o null)
create or replace function current_familia_id() returns bigint
  language sql stable security definer
  as $$ select familia_id from profiles where user_id = auth.uid() $$;

alter table profiles         enable row level security;
alter table escuelas         enable row level security;
alter table grupos           enable row level security;
alter table familias         enable row level security;
alter table alumnos          enable row level security;
alter table empresas         enable row level security;
alter table destinos         enable row level security;
alter table planes_viaje     enable row level security;
alter table documentos       enable row level security;
alter table fechas_reunion   enable row level security;
alter table votos_fecha      enable row level security;
alter table votos_plan       enable row level security;
alter table correcciones     enable row level security;
alter table planes           enable row level security;
alter table votos            enable row level security;

-- profiles: leo el mío; super_admin lee todos.
create policy "profile self read" on profiles for select using (user_id = auth.uid() or is_super_admin());
create policy "profile self update" on profiles for update using (user_id = auth.uid());
create policy "profile super_admin all" on profiles for all using (is_super_admin()) with check (is_super_admin());

-- Catálogos públicos (read anon ok)
create policy "escuelas read" on escuelas for select to anon, authenticated using (true);
create policy "empresas read" on empresas for select to anon, authenticated using (true);
create policy "destinos read" on destinos for select to anon, authenticated using (true);
create policy "planes_viaje read" on planes_viaje for select to anon, authenticated using (true);
create policy "documentos read" on documentos for select to authenticated using (true);

-- Mutación de empresas: super_admin
create policy "empresas write super" on empresas for all using (is_super_admin()) with check (is_super_admin());
create policy "escuelas write super" on escuelas for all using (is_super_admin()) with check (is_super_admin());

-- Mutación de destinos/planes/documentos: empresa_admin de la empresa dueña, o super
create policy "destinos write owner" on destinos for all
  using (is_super_admin() or is_empresa_admin(empresa_id))
  with check (is_super_admin() or is_empresa_admin(empresa_id));

create policy "planes_viaje write owner" on planes_viaje for all
  using (is_super_admin() or is_empresa_admin((select empresa_id from destinos where id = destino_id)))
  with check (is_super_admin() or is_empresa_admin((select empresa_id from destinos where id = destino_id)));

create policy "documentos write owner" on documentos for all
  using (
    is_super_admin() or
    (destino_id is not null and is_empresa_admin((select empresa_id from destinos where id = destino_id))) or
    (plan_id    is not null and is_empresa_admin((select empresa_id from destinos d join planes_viaje p on p.destino_id = d.id where p.id = plan_id)))
  ) with check (true);

-- Grupos / familias / alumnos: lectura por miembros del grupo, super_admin, y por empresas
-- (las empresas necesitan ver qué grupos están interesados — refinar en fase 2).
create policy "grupos read" on grupos for select using (true);
create policy "grupos write super" on grupos for all using (is_super_admin()) with check (is_super_admin());

create policy "familias read" on familias for select using (true);
create policy "familias insert public" on familias for insert to anon, authenticated with check (true);
create policy "familias update self" on familias for update using (
  is_super_admin() or id = current_familia_id()
);

create policy "alumnos read" on alumnos for select using (true);
create policy "alumnos write owner" on alumnos for all using (
  is_super_admin() or familia_id = current_familia_id()
) with check (
  is_super_admin() or familia_id = current_familia_id()
);

-- Fechas reunión: lectura para grupo y empresa relacionados; escritura por empresa o super.
create policy "fechas read" on fechas_reunion for select using (true);
create policy "fechas write empresa" on fechas_reunion for all
  using (is_super_admin() or is_empresa_admin(empresa_id))
  with check (is_super_admin() or is_empresa_admin(empresa_id));

create policy "votos_fecha read" on votos_fecha for select using (true);
create policy "votos_fecha write self" on votos_fecha for all
  using (is_super_admin() or familia_id = current_familia_id())
  with check (is_super_admin() or familia_id = current_familia_id());

create policy "votos_plan read" on votos_plan for select using (true);
create policy "votos_plan write self" on votos_plan for all
  using (is_super_admin() or familia_id = current_familia_id())
  with check (is_super_admin() or familia_id = current_familia_id());

create policy "correcciones insert any" on correcciones for insert to anon, authenticated with check (true);
create policy "correcciones read" on correcciones for select using (true);
create policy "correcciones update admin" on correcciones for update
  using (is_super_admin() or (plan_id is not null and is_empresa_admin((select empresa_id from destinos d join planes_viaje p on p.destino_id = d.id where p.id = plan_id))));

-- Legacy (mantener abierto mientras conviva con el frontend público actual)
create policy "planes legacy read" on planes for select to anon, authenticated using (true);
create policy "votos legacy insert" on votos for insert to anon, authenticated with check (true);
create policy "votos legacy read" on votos for select to anon, authenticated using (true);

-- =============================================================
-- Storage: bucket para documentos de viaje
-- =============================================================
insert into storage.buckets (id, name, public) values ('documentos', 'documentos', false)
  on conflict (id) do nothing;

-- RLS de storage.objects: la dueña empresa puede leer/escribir sus documentos;
-- familias autenticadas pueden leer (descargar).
create policy "documentos storage read auth" on storage.objects for select
  to authenticated using (bucket_id = 'documentos');

create policy "documentos storage write empresa" on storage.objects for insert
  to authenticated with check (bucket_id = 'documentos');

create policy "documentos storage delete owner" on storage.objects for delete
  to authenticated using (bucket_id = 'documentos' and owner = auth.uid());
