-- =============================================================
-- Mensajería empresa ↔ grupo
-- =============================================================
-- Cada par (grupo_id, empresa_id) tiene una conversación lineal. Los autores
-- pueden ser:
--   * empresa_admin de la empresa  → autor_rol = 'empresa'
--   * cualquier familia del grupo  → autor_rol = 'familia'
--
-- El hilo se "abre" implícitamente cuando la empresa propone una fecha de
-- reunión (fechas_reunion) o cuando alguna de las partes manda el primer
-- mensaje. El listado de hilos en cada UI se computa con la unión de:
--   distinct (empresa, grupo) en fechas_reunion ∪ mensajes.

create table mensajes (
  id            bigint generated by default as identity primary key,
  grupo_id      bigint not null references grupos(id) on delete cascade,
  empresa_id    bigint not null references empresas(id) on delete cascade,
  autor_user_id uuid references auth.users(id) on delete set null,
  autor_rol     text not null check (autor_rol in ('empresa', 'familia')),
  autor_nombre  text,                  -- nombre visible (apellido familia / nombre empresa)
  contenido     text not null,
  leido_empresa boolean default false, -- futuro: marcar leído por la empresa
  leido_grupo   boolean default false, -- futuro: marcar leído por el grupo
  created_at    timestamptz default now()
);
create index on mensajes (grupo_id, empresa_id, created_at);

alter table mensajes enable row level security;

-- Helper: ¿la familia del user actual pertenece al grupo dado?
create or replace function current_familia_in_grupo(p_grupo_id bigint) returns boolean
  language sql stable security definer
  as $$ select exists (
    select 1 from familias f
    where f.id = current_familia_id() and f.grupo_id = p_grupo_id
  ) $$;

-- SELECT: lee la empresa dueña, las familias del grupo, super_admin.
create policy "mensajes read" on mensajes for select using (
  is_super_admin()
  or is_empresa_admin(empresa_id)
  or current_familia_in_grupo(grupo_id)
);

-- INSERT: solo participantes válidos.
-- Validación adicional: si autor_rol='empresa' debe ser admin de esa empresa;
-- si autor_rol='familia' debe ser familia del grupo. autor_user_id queda como
-- audit trail; el cliente nunca debería pasarlo (se setea con auth.uid()).
create policy "mensajes insert empresa" on mensajes for insert with check (
  autor_rol = 'empresa' and is_empresa_admin(empresa_id)
);
create policy "mensajes insert familia" on mensajes for insert with check (
  autor_rol = 'familia' and current_familia_in_grupo(grupo_id)
);

-- UPDATE: solo para marcar leído. La empresa marca leido_empresa, la familia
-- marca leido_grupo. No permitimos editar contenido (audit trail intacto).
create policy "mensajes update empresa leido" on mensajes for update
  using (is_empresa_admin(empresa_id))
  with check (is_empresa_admin(empresa_id));
create policy "mensajes update familia leido" on mensajes for update
  using (current_familia_in_grupo(grupo_id))
  with check (current_familia_in_grupo(grupo_id));
