-- =============================================================
-- Ventas y comisiones
-- =============================================================
-- Modelo:
--   * Cuando un grupo cierra un viaje con una empresa, se carga una VENTA.
--   * La plataforma cobra una comisión (%) sobre el monto total de la venta.
--   * La comisión vive en empresas.comision_pct_default (override por venta
--     usando ventas.comision_pct).
--   * Estados de la venta:
--       borrador   → carga inicial por la empresa, datos editables
--       confirmada → la empresa cerró el trato; comisión queda fijada
--       pagada     → la empresa ya transfirió la comisión a la plataforma
--       liquidada  → super_admin auditó y cerró la operación
--       cancelada  → no se concretó
-- =============================================================

-- Comisión default por empresa (puede ser nula → cae a SETTING global del super).
alter table empresas add column comision_pct_default numeric(5,2) default 8.00;

create type venta_estado as enum ('borrador', 'confirmada', 'pagada', 'liquidada', 'cancelada');

create table ventas (
  id                  bigint generated by default as identity primary key,
  grupo_id            bigint not null references grupos(id) on delete restrict,
  empresa_id          bigint not null references empresas(id) on delete restrict,
  destino_id          bigint references destinos(id) on delete set null,
  plan_id             bigint references planes_viaje(id) on delete set null,

  cantidad_pasajeros  smallint not null check (cantidad_pasajeros > 0),
  precio_unitario     integer not null check (precio_unitario >= 0),
  monto_total         integer generated always as (cantidad_pasajeros * precio_unitario) stored,

  comision_pct        numeric(5,2) not null,
  comision_monto      integer generated always as (
    (cantidad_pasajeros * precio_unitario * comision_pct / 100)::int
  ) stored,

  estado              venta_estado not null default 'borrador',
  observaciones       text,

  created_by          uuid references auth.users(id) on delete set null,
  created_at          timestamptz default now(),
  confirmada_at       timestamptz,
  pagada_at           timestamptz,
  liquidada_at        timestamptz,
  cancelada_at        timestamptz
);
create index on ventas (empresa_id);
create index on ventas (grupo_id);
create index on ventas (estado);

-- Constraint: un grupo no puede tener más de una venta "activa" (no cancelada).
-- Esto evita doble-venta del mismo grupo a dos empresas. Se relaja durante
-- borrador (la empresa puede tener su borrador abierto incluso si otra empresa
-- también está negociando; pero solo una llega a confirmada).
create unique index ventas_grupo_activa_unica
  on ventas (grupo_id)
  where estado in ('confirmada', 'pagada', 'liquidada');

-- Sets default comision_pct desde la empresa al crear si no se pasa.
create or replace function ventas_set_default_comision() returns trigger
  language plpgsql as $$
begin
  if new.comision_pct is null then
    select coalesce(comision_pct_default, 8.00) into new.comision_pct
    from empresas where id = new.empresa_id;
  end if;
  return new;
end $$;

create trigger trg_ventas_set_comision
  before insert on ventas
  for each row execute function ventas_set_default_comision();

-- Trigger para mantener los timestamps de transición de estado coherentes.
create or replace function ventas_track_estado() returns trigger
  language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    if new.estado = 'confirmada' and new.confirmada_at is null then new.confirmada_at := now(); end if;
  elsif tg_op = 'UPDATE' and new.estado is distinct from old.estado then
    if new.estado = 'confirmada' and new.confirmada_at is null then new.confirmada_at := now(); end if;
    if new.estado = 'pagada'     and new.pagada_at     is null then new.pagada_at     := now(); end if;
    if new.estado = 'liquidada'  and new.liquidada_at  is null then new.liquidada_at  := now(); end if;
    if new.estado = 'cancelada'  and new.cancelada_at  is null then new.cancelada_at  := now(); end if;
  end if;
  return new;
end $$;

create trigger trg_ventas_track_estado
  before insert or update on ventas
  for each row execute function ventas_track_estado();

-- =============================================================
-- RLS
-- =============================================================
alter table ventas enable row level security;

-- SELECT: super_admin, empresa_admin dueña, o familia del grupo.
create policy "ventas read" on ventas for select using (
  is_super_admin()
  or is_empresa_admin(empresa_id)
  or current_familia_in_grupo(grupo_id)
);

-- INSERT/UPDATE de campos generales: empresa_admin de la empresa o super_admin.
create policy "ventas insert empresa" on ventas for insert
  with check (is_empresa_admin(empresa_id) or is_super_admin());

-- UPDATE general: empresa puede editar mientras esté en borrador/confirmada.
-- Las transiciones a pagada/liquidada las hace solo super_admin.
create policy "ventas update empresa" on ventas for update
  using (is_empresa_admin(empresa_id) and estado in ('borrador', 'confirmada'))
  with check (
    is_empresa_admin(empresa_id)
    and estado in ('borrador', 'confirmada', 'cancelada')
  );

create policy "ventas update super" on ventas for update
  using (is_super_admin()) with check (is_super_admin());

create policy "ventas delete super" on ventas for delete
  using (is_super_admin());
