-- =============================================================
-- Leads — captura de contactos en el funnel de onboarding
-- =============================================================
-- Una fila por cada visitante que dejó datos en el onboarding del frontend
-- público, esté o no su escuela cargada en el sistema. Casos:
--
--   1) Lead "frío": dejó email pero su escuela no está en `escuelas`
--      (escuela_libre tiene el nombre tipeado). El super-admin lo revisa,
--      crea la escuela, y eventualmente contacta al lead.
--
--   2) Lead "completo": completó el flujo y quedó vinculado a una familia
--      existente — familia_id apunta al row creado en `familias`.
--
-- El email es obligatorio (es la única forma de contacto persistente). El
-- resto de campos son opcionales para no bloquear conversión.
-- =============================================================

create table leads (
  id              bigint generated by default as identity primary key,
  email           text not null,
  apellido        text,
  telefono        text,
  escuela_id      bigint references escuelas(id) on delete set null,
  escuela_libre   text,                       -- nombre tipeado por el user si no encontró su escuela
  grado_buscado   text,                       -- ej: "6to A" tipeado libre antes de elegir grupo formal
  anio_egreso     smallint,
  familia_id      bigint references familias(id) on delete set null,
  origen          text default 'onboarding',  -- futuro: 'referido', 'campaña-X', etc.
  comentario      text,
  contactado      boolean default false,
  created_at      timestamptz default now()
);
create index on leads (email);
create index on leads (escuela_id);
create index on leads (created_at desc);

alter table leads enable row level security;

-- INSERT anon: cualquier visitante puede dejar su lead.
create policy "leads insert anon" on leads for insert
  to anon, authenticated with check (true);

-- SELECT/UPDATE/DELETE: super_admin solamente.
create policy "leads read super" on leads for select using (is_super_admin());
create policy "leads update super" on leads for update using (is_super_admin()) with check (is_super_admin());
create policy "leads delete super" on leads for delete using (is_super_admin());
