-- =============================================================
-- CRM básico para leads
-- =============================================================
-- Agrega a `leads`:
--   * estado: pipeline comercial (5 etapas)
--   * asignado_a: super_admin responsable
--   * next_action / next_action_at: próxima acción + fecha (para follow-ups)
--   * notas: notas internas libres
--
-- Crea `lead_actividades`: timeline de interacciones (llamadas, emails,
-- reuniones, notas), una fila por evento.
--
-- Trigger: cuando `familia_id` se setea (vino del onboarding completado),
-- el estado pasa automáticamente a 'convertido'.
-- =============================================================

create type lead_estado as enum ('nuevo', 'contactado', 'calificado', 'convertido', 'descartado');

alter table leads
  add column estado          lead_estado not null default 'nuevo',
  add column asignado_a      uuid references auth.users(id) on delete set null,
  add column next_action     text,
  add column next_action_at  timestamptz,
  add column notas           text;

-- Backfill: las filas que ya tienen familia_id se marcan convertidas.
update leads set estado = 'convertido' where familia_id is not null;

-- Trigger: cuando se setea familia_id, transicionar estado.
create or replace function leads_track_conversion() returns trigger
  language plpgsql as $$
begin
  if new.familia_id is not null and (old.familia_id is null or old.familia_id is distinct from new.familia_id) then
    if new.estado in ('nuevo', 'contactado', 'calificado') then
      new.estado := 'convertido';
    end if;
  end if;
  return new;
end $$;

create trigger trg_leads_conversion
  before update on leads
  for each row execute function leads_track_conversion();

-- Drop columna `contactado` (booleana legacy) — reemplazada por estado.
alter table leads drop column if exists contactado;

create index on leads (estado);
create index on leads (asignado_a);
create index on leads (next_action_at);

-- =============================================================
-- Actividades / timeline
-- =============================================================
create type lead_actividad_tipo as enum ('nota', 'email', 'llamada', 'whatsapp', 'reunion', 'cambio_estado', 'otro');

create table lead_actividades (
  id           bigint generated by default as identity primary key,
  lead_id      bigint not null references leads(id) on delete cascade,
  tipo         lead_actividad_tipo not null default 'nota',
  contenido    text not null,
  fecha        timestamptz not null default now(),
  autor_user_id uuid references auth.users(id) on delete set null,
  autor_nombre text,
  created_at   timestamptz default now()
);
create index on lead_actividades (lead_id, fecha desc);

alter table lead_actividades enable row level security;

create policy "actividades read super" on lead_actividades for select using (is_super_admin());
create policy "actividades insert super" on lead_actividades for insert with check (is_super_admin());
create policy "actividades update super" on lead_actividades for update using (is_super_admin()) with check (is_super_admin());
create policy "actividades delete super" on lead_actividades for delete using (is_super_admin());

-- Trigger: cuando cambia el estado de un lead, dejar un rastro en actividades.
create or replace function leads_log_estado_change() returns trigger
  language plpgsql as $$
begin
  if old.estado is distinct from new.estado then
    insert into lead_actividades (lead_id, tipo, contenido, autor_user_id)
    values (
      new.id,
      'cambio_estado',
      format('Estado %s → %s', old.estado, new.estado),
      auth.uid()
    );
  end if;
  return new;
end $$;

create trigger trg_leads_log_estado
  after update on leads
  for each row execute function leads_log_estado_change();
