-- =============================================================
-- Marketing digital · tracking + nurture + gating de chat
-- =============================================================
-- Capa de marketing sobre el modelo existente. No reemplaza nada, agrega:
--
-- 1. Campos UTM + score + last_seen_at en leads → segmentación + scoring.
-- 2. Extiende lead_actividad_tipo con valores propios de marketing
--    (`evento_funnel`, `onboarding_step`, `nurture_seen`).
-- 3. RPC `evento_funnel_log(evento, ctx, email)` para que el frontend anon
--    registre eventos del funnel (drop-off measurement).
-- 4. Trigger `leads_score_recalc` recalcula score automáticamente cuando
--    cambia el lead (familia_id NOT NULL → caliente; convertido cuando hay
--    venta confirmada en su grupo).
-- 5. Refuerza policy de mensajes: la empresa solo puede iniciar chat con
--    grupos donde existe una `fechas_reunion` confirmada o realizada.
--
-- Mantiene compatibilidad con todo lo anterior. Idempotente vía IF NOT
-- EXISTS / OR REPLACE.

-- =============================================================
-- 1. UTM + score + last_seen en leads
-- =============================================================
alter table leads
  add column if not exists utm_source   text,
  add column if not exists utm_medium   text,
  add column if not exists utm_campaign text,
  add column if not exists utm_term     text,
  add column if not exists utm_content  text,
  add column if not exists score        smallint not null default 0,
  add column if not exists last_seen_at timestamptz default now();

-- Índices para segmentación.
create index if not exists leads_utm_campaign_idx on leads(utm_campaign) where utm_campaign is not null;
create index if not exists leads_score_idx on leads(score desc);
create index if not exists leads_last_seen_idx on leads(last_seen_at desc);

-- =============================================================
-- 2. Tipos de actividad para tracking
-- =============================================================
-- ALTER TYPE ... ADD VALUE no es transaccional → corremos cada valor
-- protegido para que la migration sea idempotente.
do $$
begin
  if not exists (select 1 from pg_enum where enumlabel = 'evento_funnel'
                 and enumtypid = 'lead_actividad_tipo'::regtype) then
    alter type lead_actividad_tipo add value 'evento_funnel';
  end if;
  if not exists (select 1 from pg_enum where enumlabel = 'onboarding_step'
                 and enumtypid = 'lead_actividad_tipo'::regtype) then
    alter type lead_actividad_tipo add value 'onboarding_step';
  end if;
  if not exists (select 1 from pg_enum where enumlabel = 'nurture_seen'
                 and enumtypid = 'lead_actividad_tipo'::regtype) then
    alter type lead_actividad_tipo add value 'nurture_seen';
  end if;
end $$;

-- =============================================================
-- 3. RPC evento_funnel_log — anon puede registrar eventos del funnel
-- =============================================================
-- Toma email + evento + ctx jsonb. Encuentra (o no) el lead por email,
-- inserta una fila en lead_actividades con tipo=evento_funnel, y actualiza
-- last_seen_at. Si el lead no existe (todavía no captó email), guarda
-- silenciosamente en una tabla `eventos_anon` con ip/agent para attribution
-- posterior.

create table if not exists eventos_anon (
  id          bigint generated by default as identity primary key,
  evento      text not null,
  ctx         jsonb default '{}'::jsonb,
  session_id  text,
  created_at  timestamptz default now()
);
create index if not exists eventos_anon_session_idx on eventos_anon(session_id, created_at);
create index if not exists eventos_anon_evento_idx on eventos_anon(evento, created_at desc);

alter table eventos_anon enable row level security;
create policy "eventos_anon read super" on eventos_anon for select using (is_super_admin());
-- INSERT lo hace la RPC con security definer, no se expone la policy directa.

create or replace function evento_funnel_log(
  p_evento     text,
  p_email      text default null,
  p_ctx        jsonb default '{}'::jsonb,
  p_session_id text default null
) returns void
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  v_lead_id bigint;
begin
  if p_evento is null or btrim(p_evento) = '' then
    return; -- silencioso, no romper UX por tracking
  end if;

  -- Si vino el email, buscamos el lead. Si no, va a anon.
  if p_email is not null and btrim(p_email) <> '' then
    select id into v_lead_id from leads where lower(email) = lower(btrim(p_email)) limit 1;
  end if;

  if v_lead_id is not null then
    insert into lead_actividades (lead_id, tipo, contenido)
    values (v_lead_id, 'evento_funnel', p_evento || ' :: ' || coalesce(p_ctx::text, '{}'));

    update leads set last_seen_at = now() where id = v_lead_id;
  else
    insert into eventos_anon (evento, ctx, session_id)
    values (p_evento, coalesce(p_ctx, '{}'::jsonb), p_session_id);
  end if;
end $$;

grant execute on function evento_funnel_log(text, text, jsonb, text) to anon, authenticated;

-- =============================================================
-- 4. Score automático
-- =============================================================
-- Reglas (suma):
--   email capturado            → +10
--   escuela_id (no libre)      → +15
--   anio_egreso definido       → +5
--   familia_id (convirtió a familia)  → +30
--   actividad reciente (<7d)   → +10  (se aplica en cron / dashboard, no en trigger)
--   venta confirmada del grupo → +50  (también via cron/view, no acá)
--
-- Este trigger cubre lo que sabemos al INSERT/UPDATE del propio lead.

create or replace function leads_recalc_score() returns trigger
  language plpgsql
  set search_path = public
as $$
declare
  v_score smallint := 0;
begin
  if new.email is not null and new.email <> '' then v_score := v_score + 10; end if;
  if new.escuela_id is not null then v_score := v_score + 15; end if;
  if new.anio_egreso is not null then v_score := v_score + 5; end if;
  if new.familia_id is not null then v_score := v_score + 30; end if;
  new.score := v_score;
  return new;
end $$;

drop trigger if exists leads_score_trigger on leads;
create trigger leads_score_trigger
  before insert or update of email, escuela_id, anio_egreso, familia_id
  on leads
  for each row execute function leads_recalc_score();

-- =============================================================
-- 5. Gating de chat empresa → grupo
-- =============================================================
-- Hasta acá la policy de INSERT en mensajes solo verificaba que el
-- autor_rol='empresa' fuera admin de la empresa. Eso permite a la empresa
-- chatear con cualquier grupo aunque no haya habido reunión. Lo reforzamos:
-- la empresa solo puede iniciar/seguir un chat si existe al menos una
-- fechas_reunion entre empresa y grupo con estado in ('confirmada','realizada').
--
-- La familia puede iniciar siempre (cliente que pregunta — no es spam).

create or replace function empresa_puede_chatear(p_empresa_id bigint, p_grupo_id bigint)
returns boolean
  language sql
  stable
  security definer
  set search_path = public
as $$
  select exists (
    select 1 from fechas_reunion
    where empresa_id = p_empresa_id
      and grupo_id   = p_grupo_id
      and estado in ('confirmada', 'realizada')
  );
$$;

grant execute on function empresa_puede_chatear(bigint, bigint) to anon, authenticated;

drop policy if exists "mensajes insert empresa" on mensajes;
create policy "mensajes insert empresa" on mensajes for insert with check (
  autor_rol = 'empresa'
  and is_empresa_admin(empresa_id)
  and empresa_puede_chatear(empresa_id, grupo_id)
);
