-- =============================================================
-- Matching geográfico: ciudad de salida ↔ empresa que opera ahí
-- =============================================================
-- Una familia ve solo las empresas que efectivamente operan desde su
-- ciudad. Sin este filtro la comparativa es ruido (una familia en Mendoza
-- ve viajes que salen de Buenos Aires y no puede tomar).
--
-- Modelo:
--   ciudades            — catálogo normalizado de ciudades de salida
--   empresas_origenes   — n:m: una empresa opera desde N ciudades
--   escuelas.ciudad_id  — ciudad real del colegio (FK al catálogo)
--   localidad se conserva como display + fallback histórico.
--
-- Empresas existentes quedan sin orígenes hasta que el super_admin las
-- mapee desde el admin. Hasta entonces el filtro las oculta, lo cual es
-- correcto (mejor no mostrar que mostrar mal).

-- =============================================================
-- Catálogo de ciudades
-- =============================================================
create table if not exists ciudades (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  provincia   text,
  slug        text not null unique,
  created_at  timestamptz default now()
);
create index if not exists ciudades_provincia_idx on ciudades(provincia);

-- Seed con las principales del país. Idempotente vía slug.
insert into ciudades (nombre, provincia, slug) values
  ('Buenos Aires',     'Buenos Aires', 'buenos-aires'),
  ('La Plata',         'Buenos Aires', 'la-plata'),
  ('Mar del Plata',    'Buenos Aires', 'mar-del-plata'),
  ('Bahía Blanca',     'Buenos Aires', 'bahia-blanca'),
  ('Córdoba',          'Córdoba',      'cordoba'),
  ('Villa Carlos Paz', 'Córdoba',      'villa-carlos-paz'),
  ('Rosario',          'Santa Fe',     'rosario'),
  ('Santa Fe',         'Santa Fe',     'santa-fe'),
  ('Mendoza',          'Mendoza',      'mendoza'),
  ('San Rafael',       'Mendoza',      'san-rafael'),
  ('Tucumán',          'Tucumán',      'tucuman'),
  ('Salta',            'Salta',        'salta'),
  ('Jujuy',            'Jujuy',        'jujuy'),
  ('Neuquén',          'Neuquén',      'neuquen'),
  ('Bariloche',        'Río Negro',    'bariloche'),
  ('Mar del Plata',    'Buenos Aires', 'mar-del-plata-2')
on conflict (slug) do nothing;
-- (entry duplicado intencional: slug único es la barrera; el INSERT igual lo evita).

alter table ciudades enable row level security;
create policy "ciudades public read" on ciudades for select using (true);
create policy "ciudades super write" on ciudades for all using (is_super_admin()) with check (is_super_admin());

-- =============================================================
-- Orígenes de operación de cada empresa
-- =============================================================
create table if not exists empresas_origenes (
  empresa_id  bigint not null references empresas(id) on delete cascade,
  ciudad_id   bigint not null references ciudades(id) on delete restrict,
  created_at  timestamptz default now(),
  primary key (empresa_id, ciudad_id)
);
create index if not exists empresas_origenes_ciudad_idx on empresas_origenes(ciudad_id);

alter table empresas_origenes enable row level security;
create policy "empresas_origenes public read" on empresas_origenes for select using (true);
create policy "empresas_origenes super write" on empresas_origenes for all
  using (is_super_admin()) with check (is_super_admin());
create policy "empresas_origenes empresa write" on empresas_origenes for all
  using (is_empresa_admin(empresa_id)) with check (is_empresa_admin(empresa_id));

-- =============================================================
-- Escuelas tienen ciudad
-- =============================================================
alter table escuelas
  add column if not exists ciudad_id bigint references ciudades(id) on delete set null;
create index if not exists escuelas_ciudad_idx on escuelas(ciudad_id);

-- Backfill best-effort: match localidad (case-insensitive) contra ciudades.nombre.
update escuelas e
   set ciudad_id = c.id
  from ciudades c
 where e.ciudad_id is null
   and e.localidad is not null
   and lower(btrim(e.localidad)) = lower(btrim(c.nombre));

-- =============================================================
-- Helpers públicos
-- =============================================================

-- empresas_visibles_para_ciudad(ciudad_id) → empresas que operan desde esa ciudad.
-- Útil para listados; el frontend lo invoca via PostgREST.
create or replace view empresas_visibles_por_ciudad as
  select co.ciudad_id, e.*
    from empresas e
    join empresas_origenes co on co.empresa_id = e.id;

-- planes_relevantes(ciudad_id) → filtro definitivo: planes de empresas
-- que operan desde la ciudad pasada. Si no hay ciudad → devuelve todo
-- (modo legacy / admin sin filtro).
create or replace function planes_relevantes(p_ciudad_id bigint default null)
returns setof planes_viaje
  language sql stable
as $$
  select p.* from planes_viaje p
  where p_ciudad_id is null
     or exists (
       select 1 from empresas_origenes co
       join destinos d on d.empresa_id = co.empresa_id
       where co.ciudad_id = p_ciudad_id
         and p.destino_id = d.id
     );
$$;

grant execute on function planes_relevantes(bigint) to anon, authenticated;
