-- =============================================================
-- Familia ← N miembros (padre, madre, abuelo, etc.)
-- =============================================================
-- Hasta ahora `familias` tenía email/telefono como si fuera UN único
-- contacto. La realidad es que cualquier miembro adulto de una familia
-- puede registrarse de forma independiente. Las votaciones siguen siendo
-- por `familia_id` (un voto por unidad familiar, no por persona — eso ya
-- estaba bien diseñado). Lo que cambia es la captura de contactos.
--
-- Estrategia: nueva tabla `familia_miembros` con email/telefono por
-- persona. `familias` mantiene apellido + grupo_id como identidad
-- colectiva. Los campos email/telefono en `familias` quedan deprecados
-- pero NO se eliminan (compat con código existente).
--
-- Backfill: para cada familia con email no-null, generamos un primer
-- miembro con esos datos marcado es_principal=true.

create table if not exists familia_miembros (
  id            bigint generated by default as identity primary key,
  familia_id    bigint not null references familias(id) on delete cascade,
  user_id       uuid references auth.users(id) on delete set null,
  nombre        text,
  email         text,
  telefono      text,
  es_principal  boolean not null default false,
  created_at    timestamptz default now()
);
create index if not exists familia_miembros_familia_idx on familia_miembros(familia_id);
create index if not exists familia_miembros_email_idx on familia_miembros(lower(email)) where email is not null;
create index if not exists familia_miembros_user_idx on familia_miembros(user_id) where user_id is not null;

alter table familia_miembros enable row level security;

-- Read: super_admin, empresa_admin del grupo asociado, o la propia familia.
create policy "familia_miembros read" on familia_miembros for select using (
  is_super_admin()
  or exists (
    select 1 from familias f
    where f.id = familia_miembros.familia_id
      and f.id = current_familia_id()
  )
);

-- INSERT/UPDATE/DELETE: vía RPCs security definer; nada de exposición directa.

-- Backfill: cada familia existente con email gana un miembro principal.
insert into familia_miembros (familia_id, email, telefono, es_principal)
  select id, email, telefono, true from familias
  where email is not null and email <> ''
  on conflict do nothing;

-- =============================================================
-- RPC: unirse a una familia (crea o agrega miembro)
-- =============================================================
-- Casos:
--   1) No existe familia con (grupo_id, apellido):
--      → crea familia + primer miembro (es_principal=true).
--   2) Existe familia y existe miembro con ese email:
--      → no duplica, retorna estado actual.
--   3) Existe familia y NO existe miembro con ese email:
--      → agrega nuevo miembro (es_principal=false).
--
-- Retorna jsonb con { familia_id, miembro_id, es_principal, es_nueva_familia }.
create or replace function familia_unirse(
  p_grupo_id  bigint,
  p_apellido  text,
  p_email     text,
  p_telefono  text default null,
  p_nombre    text default null
) returns jsonb
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  v_familia_id   bigint;
  v_miembro_id   bigint;
  v_es_principal boolean := false;
  v_es_nueva     boolean := false;
  v_apellido     text   := btrim(p_apellido);
  v_email        text   := nullif(btrim(p_email), '');
begin
  if p_grupo_id is null or v_apellido = '' or v_email is null then
    raise exception 'grupo_id, apellido y email requeridos';
  end if;

  select id into v_familia_id
    from familias
   where grupo_id = p_grupo_id
     and lower(apellido) = lower(v_apellido)
   limit 1;

  if v_familia_id is null then
    -- Caso 1: familia nueva.
    insert into familias (grupo_id, apellido, email, telefono)
    values (p_grupo_id, v_apellido, v_email, nullif(btrim(p_telefono), ''))
    returning id into v_familia_id;
    v_es_nueva := true;
    v_es_principal := true;
  end if;

  -- ¿Existe miembro con este email en esta familia?
  select id into v_miembro_id
    from familia_miembros
   where familia_id = v_familia_id
     and lower(email) = lower(v_email)
   limit 1;

  if v_miembro_id is null then
    insert into familia_miembros (familia_id, email, telefono, nombre, es_principal)
    values (v_familia_id, v_email, nullif(btrim(p_telefono), ''),
            nullif(btrim(p_nombre), ''), v_es_principal)
    returning id into v_miembro_id;
  end if;

  return jsonb_build_object(
    'familia_id', v_familia_id,
    'miembro_id', v_miembro_id,
    'es_principal', v_es_principal,
    'es_nueva_familia', v_es_nueva
  );
end $$;

grant execute on function familia_unirse(bigint, text, text, text, text) to anon, authenticated;

-- =============================================================
-- RPC: contar miembros de una familia (para mostrar "ya hay N personas")
-- =============================================================
create or replace function familia_count_miembros(p_familia_id bigint)
returns integer
  language sql
  stable
  security definer
  set search_path = public
as $$
  select count(*)::int from familia_miembros where familia_id = p_familia_id;
$$;

grant execute on function familia_count_miembros(bigint) to anon, authenticated;

-- =============================================================
-- RPC: detectar familia existente por (grupo, apellido) ANTES del registro
-- =============================================================
-- Devuelve count de miembros si la familia existe, NULL si no. Útil para
-- mostrar "ya hay 2 personas registradas con este apellido en tu grado"
-- en el GrupoStep / ApellidoStep, sin tener que crear nada.
create or replace function familia_lookup(
  p_grupo_id bigint,
  p_apellido text
) returns jsonb
  language plpgsql
  stable
  security definer
  set search_path = public
as $$
declare
  v_id bigint;
  v_count int := 0;
begin
  select id into v_id
    from familias
   where grupo_id = p_grupo_id
     and lower(apellido) = lower(btrim(p_apellido))
   limit 1;

  if v_id is null then
    return jsonb_build_object('existe', false);
  end if;

  select count(*)::int into v_count from familia_miembros where familia_id = v_id;
  return jsonb_build_object('existe', true, 'familia_id', v_id, 'miembros', v_count);
end $$;

grant execute on function familia_lookup(bigint, text) to anon, authenticated;
